cronjob:
  name: "my-cronjob"
  labels:
    app: "my-cron-app"
  schedule: "0 0 * * *"  # Daily at midnight
  container:
    name: "my-cron-container"
    image: "ubuntu:latest"
    imagePullPolicy: "IfNotPresent"
    command: ["/bin/sh"]
    args: ["-c", "echo 'Hello, World!'"]
  env:
    - name: "MY_ENV_VAR"
      value: "my-env-value"
  restartPolicy: "OnFailure"
